import { hashText } from '../../dist/v1/basics/text.mjs';

/**
 * @typedef {Object} CryptoTestResult
 * @property {string} input - The original text used for hashing.
 * @property {string} algorithm - The algorithm used (e.g., 'SHA-256').
 * @property {string} actualHash - The hash generated by the function.
 * @property {string} expectedHash - The hash we expected to get.
 * @property {boolean} matches - Whether the actual hash matches the expected hash.
 */

/**
 * TestReporter provides a stylized, colorized interface for terminal output.
 * In a real project, this class should be imported from a central utility file.
 */
class TestReporter {
  #colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    green: '\x1b[32m',
    red: '\x1b[31m',
    yellow: '\x1b[33m',
    cyan: '\x1b[36m',
    magenta: '\x1b[35m',
  };

  printHeader(title) {
    console.log(
      `${this.#colors.bright}${this.#colors.cyan}========================================${this.#colors.reset}`,
    );
    console.log(`${this.#colors.bright}${this.#colors.cyan}   ${title}   ${this.#colors.reset}`);
    console.log(
      `${this.#colors.bright}${this.#colors.cyan}========================================${this.#colors.reset}\n`,
    );
  }

  /**
   * Logs the result of a cryptographic test.
   * @param {CryptoTestResult} result - The result object containing hash details.
   */
  logCryptoResult(result) {
    const isSuccess = result.matches;
    const statusSymbol = isSuccess
      ? `${this.#colors.green}✔ [PASS]${this.#colors.reset}`
      : `${this.#colors.red}✘ [FAIL]${this.#colors.reset}`;

    console.log(
      `${statusSymbol} ${this.#colors.bright}Cryptographic Verification${this.#colors.reset}`,
    );
    console.log(`   ${this.#colors.yellow}Input:     ${this.#colors.reset}${result.input}`);
    console.log(`   ${this.#colors.yellow}Algorithm: ${this.#colors.reset}${result.algorithm}`);
    console.log(`   ${this.#colors.yellow}Expected:  ${this.#colors.reset}${result.expectedHash}`);
    console.log(`   ${this.#colors.yellow}Actual:    ${this.#colors.reset}${result.actualHash}`);

    if (!isSuccess) {
      console.log(
        `${this.#colors.red}   Mismatch detected! The hash does not match the expected value.${this.#colors.reset}`,
      );
    }
    console.log('');
  }

  logError(description, error) {
    console.log(
      `${this.#colors.magenta}⚠ [ERROR]${this.#colors.reset} ${this.#colors.bright}${description}${this.#colors.reset}`,
    );
    console.log(`   ${this.#colors.red}Type: ${error.name}${this.#colors.reset}`);
    console.log(`   ${this.#colors.red}Message: ${error.message}${this.#colors.reset}\n`);
  }
}

/**
 * Executes the cryptographic test suite.
 * @returns {Promise<void>}
 */
const executeCrypto = async () => {
  const reporter = new TestReporter();
  reporter.printHeader('CRYPTO MODULE TEST');

  const testInput = 'yay';
  const algorithm = 'SHA-256';

  // The known SHA-256 hash for the string 'yay'
  const expectedHash = 'f6078ebe0c2f08c225c0349aef2fe062d71b972e3c91b9687cccdff24d0c8ac8';

  try {
    const actualHash = await hashText(testInput, algorithm);

    const result = {
      input: testInput,
      algorithm: algorithm,
      actualHash: actualHash,
      expectedHash: expectedHash,
      matches: actualHash === expectedHash,
    };

    reporter.logCryptoResult(result);
  } catch (err) {
    reporter.logError('Executing hashText function', err);
  }
};

export default executeCrypto;
